### ISSUE TITLE
Annotate PVs

### ISSUE THREAD

**Issue by speedfl** [mtougeron/k8s-pvc-tagger#66]
**Is your feature request related to a problem? Please describe.**
It could be nice to have a way to tag PV with the tags provided

**Describe the solution you'd like**
- Add commandLine argument such as `--annotate-pv`
- If `--annotate-p` is enabled, pv will be annotated with the Tags
- If enabled it must be stated in the readme that SA will be able to `patch` `PersitentVolume`
https://github.com/mtougeron/k8s-pvc-tagger/blob/main/charts/k8s-pvc-tagger/templates/rbac.yaml#L73-L76

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

I can work on an PR if needed

**Comment by mtougeron** [comment]
Can you provide an example of what the PVC would look like and the resulting PV would look like? I'd like to make sure I understand what you are requesting properly. Thanks!

**Comment by speedfl** [comment]
Hello,

Thanks a lot for your project and your fast answer. I guess you faced the same issue as us with the CSI current design which does not forward the metadata to CreateVolume request. I was writing the same operator (in Java) until I found yours!

Concerning my idea. Your question maked me think about what could be done (to be discussed).

Let's take as input 

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: touge-test
  namespace: touge
  labels:
    TeamID: "Frontend"
  annotations:
    CostCenter: "1234"
    k8s-pvc-tagger/tags: |
      {"Owner": "{{ .Labels.TeamID }}-{{ .Annotations.CostCenter }}"}
```

## Solution 1: copy only the computed tag in the annotation

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  annotations:
    Owner: Frontend-1234
spec:
  capacity:
    storage: <Size>
```

## Solution 2: Copy all labels + annotation (except kube internal one)

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    TeamID: "Frontend"
  annotations:
    CostCenter: "1234"
spec:
  capacity:
    storage: <Size>
```

## Solution 3: Copy all labels + annotation + computed tags

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    TeamID: "Frontend"
  annotations:
    CostCenter: "1234"
    k8s-pvc-tagger/tag/Owner: Frontend-1234
spec:
  capacity:
    storage: <Size>
```

## Solution 4: Add filter in the PVC of the labels annotation which can be added

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: touge-test
  namespace: touge
  labels:
    TeamID: "Frontend"
  annotations:
    CostCenter: "1234"
    k8s-pvc-tagger/tags: |
      {"Owner": "{{ .Labels.TeamID }}-{{ .Annotations.CostCenter }}"}
    k8s-pvc-tagger/annotation: |
      {"my.annotation/Owner": "{{ .Labels.TeamID }}-{{ .Annotations.CostCenter }}"}
    k8s-pvc-tagger/labels: |
      {"my.label/team": "{{ .Labels.TeamID }}-suffix"}
```

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    my.annotation/Owner: "Frontend-1234"
  annotations:
    my.annotation/team: "Frontend-suffix"
spec:
  capacity:
    storage: <Size>
```
